### ISSUE TITLE
Veure cataleg

### ISSUE THREAD

**Issue by dond72** [alexresta/scrapycrawler#1]
Quan li dono a revisar cataleg complet surt aquest error:
Traceback (most recent call last):
  File "debugDB.py", line 232, in <module>
    mainmenu()
  File "debugDB.py", line 213, in mainmenu
    egdgamesofertes()
  File "debugDB.py", line 173, in egdgamesofertes
    mainmenu()
  File "debugDB.py", line 207, in mainmenu
    mathomfullcatalog()
  File "debugDB.py", line 157, in mathomfullcatalog
    revisarfullcatalog()
  File "C:\Users\diego\Desktop\scrapycrawler-master\scrapeengines\spiders\mathomcataleg.py", line 73, in revisarfullcatalog
    process = CrawlerProcess(get_project_settings())
  File "C:\Users\diego\AppData\Local\Programs\Python\Python38\lib\site-packages\scrapy\utils\project.py", line 69, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "C:\Users\diego\AppData\Local\Programs\Python\Python38\lib\site-packages\scrapy\settings\__init__.py", line 287, in setmodule
    module = import_module(module)
  File "C:\Users\diego\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mathom'

**Comment by alexresta** [comment]
fixed!
